### ISSUE TITLE
Disables SSLPinning on Alamofire

### ISSUE THREAD

**Issue by devturhan** [pmusolino/Wormholy#62] opened 2019-08-23 11:55 UTC
Wormholy overriding certificate pinning options while using with Alamofire.
I'm using the example code block to pin certificates. While Wormholy enabled, it is not working correctly. 

```
var serverTrustPolicies: [String: ServerTrustPolicy] = [:] 
let trustPolicy = ServerTrustPolicy.pinCertificates(
    certificates: ServerTrustPolicy.certificates(),
    validateCertificateChain: true,
    validateHost: true)

serverTrustPolicies["xxxxx.com"] = trustPolicy

let configuration = URLSessionConfiguration.default

let serverTrustPolicyManager = ServerTrustPolicyManager(policies: serverTrustPolicies)

let sessionManager = SessionManager(
    configuration: configuration,
    serverTrustPolicyManager: serverTrustPolicyManager
)

return sessionManager

**Comment by pmusolino** [comment] 2019-10-30 21:20
Hi there.
I'm so sorry for the late reply, I had completely lost this issue.

We should investigate further to understand why this happens since I don't know all the dynamics under Alamofire. This is the first time that I see this problem.

**Comment by Unihilator** [comment] 2020-01-04 17:15
It's not about Alamofire. Wormholy basically doesn't allow to call urlSession(_:didReceive:completionHandler:) delegate method which handles session level challenges. You can reproduce it by simply implement session delegate with the method above.

**Comment by Unihilator** [comment] 2020-01-04 19:15
Fixed in [this PR](https://github.com/pmusolino/Wormholy/pull/71). Feel free to review

**Comment by mateuszdetko** [comment] 2020-09-03 18:55
Any update? I have the same issue.

**Comment by quifago** [comment] 2021-07-11 20:36
any update?

**Comment by pmusolino** [comment] 2021-07-12 09:39
I still have to look at this issue in detail but if you have time, feel free to contribute ;)

**Closed** 2021-11-01 18:30 UTC
Labels: enhancement, help wanted
